const exceljs = require('exceljs');
const reportsRepository = require('../repositories/reportsRepository');
const logger = require('../../../config/logger');

const getBranchSnapshot = async (tenantId) => {
  return await reportsRepository.getBranchSnapshot(tenantId);
};

const generateBranchSnapshotExcel = async (tenantId, generatedBy) => {
  const data = await reportsRepository.getBranchSnapshot(tenantId);

  const workbook = new exceljs.Workbook();
  workbook.creator = 'Lead Management System';
  workbook.lastModifiedBy = generatedBy;
  workbook.created = new Date();
  workbook.modified = new Date();

  const sheet = workbook.addWorksheet('Branch Summary');

  sheet.columns = [
    { header: 'Branch Name', key: 'branch_name', width: 25 },
    { header: 'Branch Code', key: 'branch_code', width: 15 },
    { header: 'Manager', key: 'manager_name', width: 20 },
    { header: 'City', key: 'city', width: 15 },
    { header: 'State', key: 'state', width: 15 },
    { header: 'Status', key: 'status', width: 15 },
    { header: 'Total Leads', key: 'total_leads', width: 15 },
    { header: 'Qualified Leads', key: 'qualified_leads', width: 18 },
    { header: 'Contacted Leads', key: 'contacted_leads', width: 18 },
    { header: 'In Negotiation', key: 'negotiation_leads', width: 16 },
    { header: 'Won Leads', key: 'won_leads', width: 15 },
    { header: 'Lost Leads', key: 'lost_leads', width: 15 },
    { header: 'Conversion %', key: 'conversion_pct', width: 15 },
    { header: 'Expected Revenue', key: 'expected_revenue', width: 20 },
    { header: 'Won Revenue', key: 'won_revenue', width: 20 },
    { header: 'Teams', key: 'teams_count', width: 10 },
    { header: 'Team Leaders', key: 'team_leaders_count', width: 15 },
    { header: 'Developers', key: 'developers_count', width: 15 },
  ];

  // Style header row
  sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E293B' } };
  sheet.getRow(1).alignment = { vertical: 'middle', horizontal: 'center' };

  data.forEach((row) => {
    const totalLeads = Number(row.total_leads) || 0;
    const wonLeads = Number(row.won_leads) || 0;
    const conversionPct = totalLeads > 0 ? ((wonLeads / totalLeads) * 100).toFixed(1) + '%' : '0%';

    sheet.addRow({
      branch_name: row.branch_name,
      branch_code: row.branch_code,
      manager_name: row.manager_name || 'Unassigned',
      city: row.city,
      state: row.state,
      status: row.status,
      total_leads: totalLeads,
      qualified_leads: Number(row.qualified_leads) || 0,
      contacted_leads: Number(row.contacted_leads) || 0,
      negotiation_leads: Number(row.negotiation_leads) || 0,
      won_leads: wonLeads,
      lost_leads: Number(row.lost_leads) || 0,
      conversion_pct: conversionPct,
      expected_revenue: Number(row.expected_revenue) || 0,
      won_revenue: Number(row.won_revenue) || 0,
      teams_count: Number(row.teams_count) || 0,
      team_leaders_count: Number(row.team_leaders_count) || 0,
      developers_count: Number(row.developers_count) || 0,
    });
  });

  // Format revenue columns
  sheet.getColumn('expected_revenue').numFmt = '"₹"#,##0.00';
  sheet.getColumn('won_revenue').numFmt = '"₹"#,##0.00';

  // Metadata block at the bottom
  sheet.addRow([]);
  sheet.addRow(['Metadata:']);
  sheet.addRow(['Last Generated Time:', new Date().toISOString()]);
  sheet.addRow(['Generated By:', generatedBy]);
  sheet.addRow(['Tenant ID:', tenantId]);

  return await workbook.xlsx.writeBuffer();
};

module.exports = {
  getBranchSnapshot,
  generateBranchSnapshotExcel,
};
