/**
 * Teams Module Constants
 */

const ERROR_CODES = {
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  TEAM_LEADER_NOT_FOUND: 'TEAM_LEADER_NOT_FOUND',
  DEVELOPER_NOT_FOUND: 'DEVELOPER_NOT_FOUND',
  DUPLICATE_TEAM_NAME: 'DUPLICATE_TEAM_NAME',
  DUPLICATE_EMPLOYEE_ID: 'DUPLICATE_EMPLOYEE_ID',
  BRANCH_MISMATCH: 'BRANCH_MISMATCH'
};

const TASK_STATUS = {
  OPEN: 'Open',
  PENDING: 'Pending',
  IN_PROGRESS: 'In Progress',
  DONE: 'Done',
  CANCELLED: 'Cancelled'
};

module.exports = {
  ERROR_CODES,
  TASK_STATUS
};
