/**
 * Developer Module Constants
 */

const ERROR_CODES = {
  DEVELOPER_NOT_FOUND: 'DEVELOPER_NOT_FOUND',
  DUPLICATE_EMPLOYEE_ID: 'DUPLICATE_EMPLOYEE_ID',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  BRANCH_MISMATCH: 'BRANCH_MISMATCH'
};

module.exports = {
  ERROR_CODES
};
