/**
 * Authentication Module Constants
 */

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  TEAM_LEADER: 'TEAM_LEADER',
  DEVELOPER: 'DEVELOPER'
};

const ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_MISSING: 'TOKEN_MISSING',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INACTIVE_USER: 'INACTIVE_USER',
  DELETED_USER: 'DELETED_USER',
  INVALID_SESSION: 'INVALID_SESSION',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  VALIDATION_ERROR: 'VALIDATION_ERROR'
};

module.exports = {
  ROLES,
  ERROR_CODES
};
