-- ==========================================
-- PostgreSQL Reference Seed Data
-- Project: CRM Lead Management SaaS
-- ==========================================

-- NOTE: This script assumes the schema.sql has already been executed.

-- 1. Insert Global Roles
INSERT INTO roles (id, name, description) VALUES
  ('11111111-1111-1111-1111-111111111111', 'SUPER_ADMIN', 'System wide super administrator'),
  ('22222222-2222-2222-2222-222222222222', 'ADMIN', 'Tenant specific branch manager/admin'),
  ('33333333-3333-3333-3333-333333333333', 'TEAM_LEADER', 'Manages a specific team of developers'),
  ('44444444-4444-4444-4444-444444444444', 'DEVELOPER', 'Executes tasks and handles lead requirements')
ON CONFLICT (name) DO NOTHING;

-- 2. Insert Base Permissions
INSERT INTO permissions (id, name, description) VALUES
  ('10000000-0000-0000-0000-000000000001', 'leads:read', 'Can view leads'),
  ('10000000-0000-0000-0000-000000000002', 'leads:write', 'Can create and edit leads'),
  ('10000000-0000-0000-0000-000000000003', 'tasks:read', 'Can view tasks'),
  ('10000000-0000-0000-0000-000000000004', 'tasks:write', 'Can create and edit tasks'),
  ('10000000-0000-0000-0000-000000000005', 'branches:read', 'Can view branches'),
  ('10000000-0000-0000-0000-000000000006', 'branches:write', 'Can manage branches'),
  ('10000000-0000-0000-0000-000000000007', 'users:read', 'Can view users'),
  ('10000000-0000-0000-0000-000000000008', 'users:write', 'Can manage users')
ON CONFLICT (name) DO NOTHING;

-- 3. Map Roles to Permissions
-- Give Admin all permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p WHERE r.name = 'ADMIN'
ON CONFLICT DO NOTHING;

-- Give Team Leader read/write on leads and tasks, and read on users
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p 
WHERE r.name = 'TEAM_LEADER' AND p.name IN ('leads:read', 'leads:write', 'tasks:read', 'tasks:write', 'users:read')
ON CONFLICT DO NOTHING;

-- Give Developer read on leads and read/write on tasks
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p 
WHERE r.name = 'DEVELOPER' AND p.name IN ('leads:read', 'tasks:read', 'tasks:write')
ON CONFLICT DO NOTHING;


-- ==========================================
-- DEMO / SEED DATA FOR A SINGLE TENANT
-- ==========================================

-- 4. Create a Default Tenant
INSERT INTO tenants (id, name, status) 
VALUES ('aaaa0000-0000-0000-0000-000000000000', 'Kosqu Corporate Software', 'Active')
ON CONFLICT DO NOTHING;

-- 5. Create Sample Users (Password hash is typically generated by bcrypt. Used 'mockhash' for demo)
INSERT INTO users (id, tenant_id, role_id, email, password_hash, first_name, last_name, status) VALUES
  -- Super Admin
  ('bbbb0000-0000-0000-0000-000000000001', 'aaaa0000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'admin@antigravity.com', '$2b$10$uoNhEr5tKgfCj3S/pzIzX.YmDi6aL2t/GDhkdxq/vUS4.5d6xvhhW', 'System', 'Admin', 'Active'),
  
  -- Branch Manager (Admin)
  ('bbbb0000-0000-0000-0000-000000000002', 'aaaa0000-0000-0000-0000-000000000000', '22222222-2222-2222-2222-222222222222', 'pooja.hegde@kosqueadv.com', '$2b$10$PAw9t24XGGihZcRo9BfZKunsZjhLyJr2gW7uFs5RPb1.RY5AUFGw6', 'Pooja', 'Hegde', 'Active'),
  
  -- Team Leader
  ('bbbb0000-0000-0000-0000-000000000003', 'aaaa0000-0000-0000-0000-000000000000', '33333333-3333-3333-3333-333333333333', 'rohan.verma@kosqu.com', '$2b$10$mWNj2bzDHMSW3vh7mPObnOliekyEi58GRsxVklWQ7hFJwJ.hOjXkK', 'Rohan', 'Verma', 'Active'),
  
  -- Developer
  ('bbbb0000-0000-0000-0000-000000000004', 'aaaa0000-0000-0000-0000-000000000000', '44444444-4444-4444-4444-444444444444', 'aarav.mehta@kosqu.com', '$2b$10$F5PIkVgLfMhRXvF9O1YYmO2X9JGzDYGXkcEgwMwTOPjGz8NCCYZqC', 'Aarav', 'Mehta', 'Active')
ON CONFLICT (tenant_id, email) DO NOTHING;

-- 6. Create Branches
INSERT INTO branches (id, tenant_id, manager_id, branch_name, branch_code, city, company_name) VALUES
  ('cccc0000-0000-0000-0000-000000000001', 'aaaa0000-0000-0000-0000-000000000000', 'bbbb0000-0000-0000-0000-000000000002', 'Kosque Advertisement', 'KA004', 'Mumbai', 'Kosque Media'),
  ('cccc0000-0000-0000-0000-000000000002', 'aaaa0000-0000-0000-0000-000000000000', NULL, 'Kosqu Corporate Office', 'KQ001', 'Pune', 'Kosqu Software')
ON CONFLICT (tenant_id, branch_code) DO NOTHING;

-- 7. Create Teams
INSERT INTO teams (id, tenant_id, branch_id, team_name, department) VALUES
  ('dddd0000-0000-0000-0000-000000000001', 'aaaa0000-0000-0000-0000-000000000000', 'cccc0000-0000-0000-0000-000000000001', 'Mumbai Avengers', 'CRM Development')
ON CONFLICT DO NOTHING;

-- 8. Map Profiles
-- Team Leader mapping
INSERT INTO team_leaders (tenant_id, user_id, team_id, employee_id, designation) VALUES
  ('aaaa0000-0000-0000-0000-000000000000', 'bbbb0000-0000-0000-0000-000000000003', 'dddd0000-0000-0000-0000-000000000001', 'EMP101', 'Senior Team Leader')
ON CONFLICT (user_id) DO NOTHING;

-- Developer mapping
INSERT INTO developers (tenant_id, user_id, team_id, employee_id, skills) VALUES
  ('aaaa0000-0000-0000-0000-000000000000', 'bbbb0000-0000-0000-0000-000000000004', 'dddd0000-0000-0000-0000-000000000001', 'DEV1001', 'React, Node.js, PostgreSQL')
ON CONFLICT (user_id) DO NOTHING;
